mood/urls.py
from django.urls import path
from . import views
from .views import MoodCreateView, MoodListView, MoodDetailView, MoodUpdateView, MoodDeleteView

urlpatterns = [
    path('moods/', MoodListView.as_view(), name='mood-home'),
    path('moods/<int:pk>', MoodDetailView.as_view(), name='mood-detail'),  # pk primary key, int integer
    path('moods/<int:pk>/edit/', MoodUpdateView.as_view(), name='mood-edit'),
    path('moods/<int:pk>/delete/', MoodDeleteView.as_view(), name='mood-delete'),
    # path('moods/create', MoodCreateView.as_view(), name='mood-create'),
    path('moods/new/', views.mood_new, name='mood-new'),
    path('calendar/', views.display, name='mood-display'),
]

post/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import (
    PostListView,
    PostDetailView, PostOptionView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    GratitudePostListView, QuestionPostListView,
    UserPostSave, UserPostHide, PostOptionEdit,
    SavePostListView, HidePostListView,
    HistoryListView
)
from . import views

urlpatterns = [
    # landing page
    path('', views.landing, name='home'),

    # list views
    path('posts/', PostListView.as_view(), name='post-list'),
    path('free/', GratitudePostListView.as_view(), name='post-free-journal'),
    path('guided/', QuestionPostListView.as_view(), name='post-guided-journal'),
    path('saved/', SavePostListView.as_view(), name='post-saved'),
    path('history/', HistoryListView.as_view(), name='post-history'),

    # post viewing and operations
    path('posts/<int:pk>', PostDetailView.as_view(), name='post-detail'),  # pk primary key, int integer
    path('posts/new/', PostCreateView.as_view(), name='post-create'),
    path('posts/<int:pk>/edit/', PostUpdateView.as_view(), name='post-edit'),
    path('posts/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),

    # saving and hiding posts
    path('posts/opt/<int:pk>/<str:option>/', PostOptionView.as_view(), name='post-option-detail'),
    path('posts/optdel/<int:pk>/<str:option>/', PostOptionEdit, name='post-option-edit'),
    path('posts/<int:pk>/<str:user>/save/', UserPostSave, name='post-save'),
    path('posts/<int:pk>/<str:user>/hide/', UserPostHide, name='post-hide'),

    # registration
    path('signup/', views.signup, name='signup'),
    path('login/', LoginView.as_view(), name='login'),

    # search posts
    path('search', views.search, name='search'),

    # reset db
    path('reset', views.reset)
]

vibe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
    path('', include('mood.urls')),
    path('', include('customizer.urls')),
    path('', include('django.contrib.auth.urls'))

]

post/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    # has own table in db
    POST_TYPES = (
        ("Gratitude", 'Gratitude'),
        ("Question", 'Question'),
    )
    title = models.CharField(max_length=100)
    content = models.TextField() 
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post_type = models.CharField(max_length=20, choices=POST_TYPES, default=POST_TYPES[0])
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
          return reverse('post-detail', kwargs={'pk': self.pk})

class UserPostOptions(models.Model):

    OPTION_TYPES = (
        ("Save", "Save"),
        ("Hide", "Hide"),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    option_type = models.CharField(max_length=4, choices=OPTION_TYPES, default=OPTION_TYPES[0])
    date_created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{str(self.user.username)} [{self.option_type}] {str(self.post)} on {str(self.date_created)}"

post/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', )

post/views.py
import random
import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied, ObjectDoesNotExist
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)

from .anonlist import rand_anon_author
from .forms import SignUpForm
from .models import Post, UserPostOptions
from django.contrib.auth.models import User
from django.core.management import call_command
from django.db.models import Q
from mood.models import Mood
from customizer.models import Customizer
from django.utils import timezone
import os

# ==============HOME PAGE================
# Landing Page
def landing(request):
    number_of_posts = 0
    entered_mood_today = None
    if request.user.is_authenticated:
        number_of_posts = Post.objects.filter(date_posted__date=timezone.now()).filter(author_id=request.user.id).count()
        entered_mood_today = Mood.objects.filter(author=request.user).filter(date_posted__exact=timezone.now()).first
        context = dict()
        setting = Customizer.objects.filter(user=request.user)
        if setting:
            setting = setting[0]
            context.update({"nav_color": setting.theme_nav,
                            "bg_color": setting.theme_background,
                            "font_size": setting.font_size,
                            "font_style": setting.font_style})
        context.update({'title': 'Home', 'post_count': number_of_posts, 'mood_today': entered_mood_today})
        return render(request, 'landing.html', context)
    else:
        return redirect('login')

# ==============HELPER FUNCTIONS================
# Helper class, requires login and displays Permission denied error
class CustomLoginRequiredMixin(LoginRequiredMixin):
    """ The LoginRequiredMixin extended to add a relevant message to the
    messages framework by setting the ``permission_denied_message``
    attribute. """
    permission_denied_message = 'You have to be logged in to perform that action'
    user_permission_denied_message = 'You do not have permission to perform that action'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.add_message(request, messages.WARNING,
                                 self.permission_denied_message)
            return self.handle_no_permission()
        return super(CustomLoginRequiredMixin, self).dispatch(
            request, *args, **kwargs
        )

# Posts within 24 hours
class RecentListView(ListView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["rand_name"] = rand_anon_author()
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if not self.request.user.is_superuser:
            queryset = queryset.filter(date_posted__gt=timezone.now() - datetime.timedelta(days=1))
            # yes, bad admin bad, no hiding
            hide_set = UserPostOptions.objects.filter(user=self.request.user, option_type="Hide").values('post')
            queryset = queryset.exclude(pk__in=hide_set)
        return queryset

class CustomizerLoader():
    def get_context_data(self):
        context = dict()
        setting = Customizer.objects.filter(user=self.request.user)
        if setting:
            setting = setting[0]
            context.update({"nav_color": setting.theme_nav,
                            "bg_color": setting.theme_background,
                            "font_size": setting.font_size,
                            "font_style": setting.font_style})
        return context

# Reset the DB
def reset(request):
    DJANGO_ENV = os.environ.get('DJANGO_ENV')
    if DJANGO_ENV == "production":
        raise ValueError("Unable to reset database in production")

    print("reset db", DJANGO_ENV)
    call_command("truncate", "--apps", "post", "mood")
    call_command("loaddata", "db/fixtures/moods.json")
    call_command("loaddata", "db/fixtures/posts.json")
    return render(request, 'reset.html', {'title': 'Reset DB'})

# ==============STANDARD POSTS LIST VIEW================
# My Posts page, lists all recent posts
class PostListView(CustomLoginRequiredMixin, RecentListView, CustomizerLoader):
    model = Post
    login_url = '/login/'

    template_name = 'post/home.html'  # <app>/<model>_<viewtype>/html
    context_object_name = 'posts'
    ordering = ['-date_posted']

    def get_context_data(self, **kwargs):
        context = RecentListView.get_context_data(self, **kwargs)
        context.update(CustomizerLoader.get_context_data(self))
        return context

# My Gratitude Posts page, lists all recent gratitude type posts
class GratitudePostListView(CustomLoginRequiredMixin, RecentListView, CustomizerLoader):
    model = Post
    login_url = '/login/'

    template_name = 'post/home.html'  # <app>/<model>_<viewtype>/html
    context_object_name = 'posts'
    ordering = ['-date_posted']

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_type'] = "Gratitude"
        # This chonker returns a tuple of post ids that the user has saved
        context['saved_posts'] = list(UserPostOptions.objects.filter(user=self.request.user, option_type="Save").values_list('post', flat=True))
        context['save_str'] = "Save"
        context.update(CustomizerLoader.get_context_data(self))
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        items = queryset.filter(post_type="Gratitude")
        return items

# My Reflective Question Posts page, lists all recent gratitude type posts
class QuestionPostListView(CustomLoginRequiredMixin, RecentListView, CustomizerLoader):
    model = Post
    login_url = '/login/'

    template_name = 'post/home.html'  # <app>/<model>_<viewtype>/html
    context_object_name = 'posts'
    ordering = ['-date_posted']

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_type'] = "Reflective Question"
        # This chonker returns a tuple of post ids that the user has saved
        context['saved_posts'] = list(UserPostOptions.objects.filter(user=self.request.user, option_type="Save").values_list('post', flat=True))
        context['save_str'] = "Save"
        context.update(CustomizerLoader.get_context_data(self))
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        user_items = queryset.filter(post_type="Question").filter(author=self.request.user)  # .values('title')
        items = queryset.filter(title__in=list(user_items)).filter(post_type="Question")
        return items

# User's history of posts
class HistoryListView(CustomLoginRequiredMixin, ListView, CustomizerLoader):
    model = Post
    login_url = '/login/'

    template_name = 'post/home.html'  # <app>/<model>_<viewtype>/html
    context_object_name = 'posts'
    ordering = ['-date_posted']

    def get_context_data(self, **kwargs):
        context = ListView.get_context_data(self, **kwargs)
        context.update(CustomizerLoader.get_context_data(self))
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(author_id=self.request.user.id)


# View all posts saved, not time limited
class SavePostListView(CustomLoginRequiredMixin, ListView, CustomizerLoader):
    model = UserPostOptions
    login_url = '/login/'

    template_name = 'post/post_options.html'
    context_object_name = 'posts'
    ordering = ['-date_created']

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["rand_name"] = rand_anon_author()
        context['option_name'] = "Saved"
        context['option_type'] = "Save"
        context.update(CustomizerLoader.get_context_data(self))
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        saved_posts = queryset.filter(user=self.request.user, option_type="Save").values('post')
        actual_posts = []
        for post in saved_posts:
            actual_posts.append(Post.objects.get(pk=post['post']))
        return actual_posts

# View all hidden posts
class HidePostListView(CustomLoginRequiredMixin, ListView, CustomizerLoader):
    model = UserPostOptions
    login_url = '/login/'

    template_name = 'post/post_options.html'
    context_object_name = 'posts'
    ordering = ['-date_created']

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["rand_name"] = rand_anon_author()
        context['option_name'] = "Hidden"
        context['option_type'] = "Hide"
        context.update(CustomizerLoader.get_context_data(self))
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        saved_posts = queryset.filter(user=self.request.user, option_type="Hide").values('post')
        actual_posts = []
        for post in saved_posts:
            actual_posts.append(Post.objects.get(pk=post['post']))
        return actual_posts

# Show details about one post
class PostDetailView(CustomLoginRequiredMixin, DetailView, CustomizerLoader):
    model = Post
    login_url = '/login/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # This chonker returns a tuple of post ids that the user has saved/hidden
        context['saved_posts'] = list(UserPostOptions.objects.filter(user=self.request.user, option_type="Save").values_list('post', flat=True))

post/templates/post/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'post/main.css' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>

  {% if title %}
    <title>My Diary- {{ title }}</title>
  {% else %}
    <title>My Diary</title>
  {% endif %}
  
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Vibe</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/gratitude">Gratitude</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/question">Question</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/personal">Personal</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/moods">Moods</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/about">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
    
    <br>
    <div class="container">
      {% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
          <!--Child templates can override the below block -->
          {% block content %}{% endblock %}
    </div>
  </div>
</body>
</html>

post/templates/post/home.html
{% extends "base.html" %}
{% block content %}

    <div id="feed-header">
        <!-- Header for the type of feed -->
        {% if post_type != None %}
            {% if post_type == "Gratitude" %}
                <h1>{% if user.id %}{% endif %} Free Journaling Entries</h1>
            {% else %}
                <h1>{% if user.id %}{% endif %} Guided Journaling Entries</h1>
            {% endif %}
        {% else %}
            <h1>{% if user.id %}My{% endif %} Posts</h1>
        {% endif %}

        <!-- Button to create new post -->
        {% if post_type == "Gratitude" %}
            <a id="new-post-btn" class="btn btn-success" href="{% url 'post-create' %}?title=0" role="button"><i
                    class="fas fa-plus"></i> New Entry</a>
        {% elif post_type == "Reflective Question" %}
            <a id="new-post-btn" class="btn btn-success" href="{% url 'post-create' %}?title=1" role="button"><i
                    class="fas fa-plus"></i> New Entry</a>
        {% else %}
            {# All Posts Page #}
            <div class="btn-group" role="group" aria-label="Button group with nested dropdown" style="float:right;">
                <div class="btn-group" role="group">
                    <button id="new-post-btn" type="button" class="btn btn-success dropdown-toggle"
                            data-bs-toggle="dropdown"
                            aria-expanded="false">
                        <i class="fas fa-plus"></i> New Entry
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                        <li><a class="dropdown-item" href="{% url 'post-create' %}?title=1">Guided Entry</a></li>
                        <li><a class="dropdown-item" href="{% url 'post-create' %}?title=0">Free Entry</a></li>
                    </ul>
                </div>
            </div>
        {% endif %}
    </div>

    <div>
        {# Display message if any exist (e.g. permission denied) #}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    </div>

    {% if posts.count == 0 %}
        {% if post_type == "Reflective Question" %}
            <p>There are no posts here yet. Answer a question to see what others have posted!</p>
        {% elif post_type == "Gratitude" %}
            <p>There are no posts here yet. Share your experiences with others!</p>
        {% endif %}
    {% else %}
        {% if post_type == "Gratitude" %}
            <p>Share your experiences with others!</p>
        {% endif %}
    {% endif %}

    {% for post in posts %}
        <div class="card post-container">
            <div class="card feed-card" onclick='location.href="{% url 'post-detail' post.id %}"'>
                <article>
                    <h2 class="card-title">{{ post.title }}</h2>
                    {# Django Date Documentation: https://docs.djangoproject.com/en/2.0/ref/templates/builtins/#date #}
                    <p class="card-subtitle">
                        By
                        {% if user.is_superuser or user == post.author %}
                            {# May want to style the user differently #}
                            <i>{{ post.author }}</i>
                        {% else %}
                            {{ rand_name|random }}
                        {% endif %}
                        {{ post.date_posted|date:"D, M d, Y" }}
                    </p>
                    <p class="card-text">{{ post.content|truncatewords:50 }}</p>
                </article>
                <nav>
                    {% if post.id in saved_posts %}
                        <div class="save-btn-group">
                            <a name="unsave-btn" class="btn btn-sm"
                               href="{% url 'post-option-edit' post.id save_str %}?next={{ request.path|urlencode }}">
                                <i class="fas fa-bookmark"></i>
                            </a>
                        </div>
                    {% else %}
                        <div class="save-btn-group">
                            <a name="save-btn" class="btn btn-sm"
                               href="{% url 'post-save' post.id user.username %}?next={{ request.path|urlencode }}">
                                <i class="far fa-bookmark"></i>
                            </a>
                        </div>
                    {% endif %}

                    <div class="hide-btn-group">
                        <a name="hide-btn" class="btn btn-sm"
                           href="{% url 'post-hide' post.id user.username %}?next={{ request.path|urlencode }}">
                            <i class="far fa-eye-slash"></i>
                        </a>
                    </div>
                </nav>
            </div>
        </div>
    {% endfor %}

<script>
    window.setTimeout(function () {
    location.reload();
}, 3000000);
</script>
{% endblock content %}

post/templates/post/post_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}"?</h2>
            </fieldset>
            <div class="form-group">
                <a class="btn btn-light" id="cancel-btn" href="{% url 'post-detail' object.id %}">Cancel</a>
                <button class="btn btn-primary" id="delete-btn" type="submit">Delete</button>
            </div>
        </form>
    </div>
{% endblock content %}

post/templates/post/post_detail.html
{% extends "base.html" %}
{% block content %}
    <div>
        {# Display message if any exist (e.g. permission denied) #}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    </div>

    <div id="post-details">
        <!-- Contents of the post -->
        <article>
            <h2>{{ object.title }}</h2>
            <p>
                <i>
                    By 
                    <b>
                        {% if user.is_superuser or user == object.author %}
                            {{ object.author }}
                        {% else %}
                            Anonymous
                        {% endif %}
                    </b>
                    on {{ object.date_posted|date:"d/m/Y" }} 
                </i>
            </p>
            <p>{{ object.content }}</p>
        </article>

        <!-- Buttons representing user actions -->
        {% if user == object.author or user.is_superuser %}
        <div class="post-actions">
            {# Precedence (a and b) or (a and c) #}
            <a id="edit-btn" class="btn btn-light" href="{% url 'post-edit' object.id %}?next={{ request.path|urlencode }}"><i class="fa fa-edit"></i> Edit</a>
            <a id="delete-btn" class="btn btn-light post-delete" data-confirm="Are you sure you want to delete the post?"
               rel="nofollow" data-method="delete" href="{% url 'post-delete' object.id %}?next={{ request.path|urlencode }}"><i class="fa fa-trash"></i> Delete</a>
        </div>
        {% else %}
            <div class="post-actions">
                {% if object.id in saved_posts %}
                    <a name="unsave-btn" class="btn btn-sm" href="{% url 'post-option-edit' object.id save_str %}?next={{ request.path|urlencode }}">Unsave</a>
                {% else %}
                    <a name="save-btn" class="btn btn-sm" href="{% url 'post-save' object.id user.username %}">Save</a>
                {% endif %}

                {% if object.id in hidden_posts %}   
                    <a name="unhide-btn" class="btn btn-sm" href="{% url 'post-option-edit' object.id hide_str %}?next={{ request.path|urlencode }}">Unhide</a>
                {% else %}
                    <a name="hide-btn" class="btn btn-danger btn-sm" href="{% url 'post-hide' object.id user.username %}">Hide</a>
                {% endif %}
                    
            </div>
        {% endif %}
    </div>

{% endblock content %}

post/templates/post/post_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% block content %}

    <div id="post-form" class="content-selection">

        {# Display Warning messages #}
        <div>
            {# Display message if any exist (e.g. permission denied) #}
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        </div>

        {# Title display for different modes #}
        {% if post.id %}
            <legend>Editing Entry</legend>
        {% else %}
            <legend>New Entry</legend>
        {% endif %}

        <form method="POST">
            {% csrf_token %}

            <fieldset class="form-group">
                <label class="">Title <span class="mandatory">*</span></label>
                <div id="id_title">{{ form.title }}</div>
            </fieldset>

            <fieldset class="form-group">
                <label class="">Content <span class="mandatory">*</span></label>
                {# post.content is empty if this is a new post #}
                <textarea id="id_content" name="content">{{ post.content }}</textarea>
            </fieldset>

                <fieldset class="form-group" {% if settings.DJANGO_ENV != "development" %}style="display:none;"{% endif %}>
                    <label class="">Post type <span class="mandatory">*</span></label>
                    <div id="id_post_type">
                        {% if post.id %}
                            {{ post.post_type }}
                        {% else %}
                            {{ form.post_type }}
                        {% endif %}
                    </div>
                </fieldset>

                <fieldset class="form-group" {% if settings.DJANGO_ENV != "development" %}style="display:none;"{% endif %}>
                    <label class="">Date <span class="mandatory">*</span></label>
                    <div id="id_date">
                        {% if post.id %}
                            <input value="{{ object.date_posted | date:'Y-m-d' }}T{{ object.date_posted | date:'H' }}:{{ object.date_posted | date:'i' }}"
                                   type="datetime-local"
                                   name="date_posted"/>
                            </input>
                        {% else %}
                            {{ form.date_posted }}
                        {% endif %}
                    </div>
                </fieldset>

            <nav class="edit-actions">
                <button id="save-btn" class="btn btn-primary confirm-button" type="submit">Post</button>
                {% if form.post_type.value == "Gratitude" %}
                    <a href="{% url 'post-free-journal' %}" id="post-cancel-btn" class="btn btn-light">Cancel</a>
                {% else %} {# Reflective Question #}
                    <a href="{% url 'post-guided-journal' %}" id="post-cancel-btn" class="btn btn-light">Cancel</a>
                {% endif %}
            </nav>

        </form>

    </div>

{% endblock content %}

post/templates/post/post_option_detail.html
{% extends "base.html" %}
{% block content %}
    <div>
        {# Display message if any exist (e.g. permission denied) #}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    </div>

    <div>
        <div class="post-actions">
            {% if option_type == "Save" %}
                <a id="unsave-btn" class="btn btn-danger btn-sm" href="{% url 'post-option-edit' object.id option_type %}">Unsave</a>
            {% else %}
                <a id="unhide-btn" class="btn btn-danger btn-sm" href="{% url 'post-option-edit' object.id option_type %}">Unhide</a>
            {% endif %}
        </div>

        <h2>{{ object.title }}</h2>
        <p>
            <i>
                By 
                <b>
                    {% if user.is_superuser or user == object.author %}
                        {{ object.author }}
                    {% else %}
                        Anonymous
                    {% endif %}
                </b>
                on {{ object.date_posted|date:"d/m/Y" }} 
            </i>
        </p>
        <p>{{ object.content }}</p>
    </div>

{% endblock content %}

post/templates/post/post_options.html
{% extends "base.html" %}
{% block content %}

    {% if user.id %}
        <div id="feed-header">
            <h1>My {{ option_name }} Posts</h1>
        </div>
    {% else %}
        <h2>You must login to use this feature</h2>
    {% endif %}

    {# Display message if any exist (e.g. permission denied) #}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    {# Display posts #}
    {% for post in posts %}
        <div class="card post-container">
            <div class="card feed-card" onclick='location.href="{% url 'post-detail' post.id %}"'>
                <article>
                    <h2 class="card-title">{{ post.title }}</h2>
                    {# Django Date Documentation: https://docs.djangoproject.com/en/2.0/ref/templates/builtins/#date #}
                    <p class="card-subtitle">
                        By
                        {% if user.is_superuser or user == post.author %}
                            {# May want to style the user differently #}
                            <i>{{ post.author }}</i>
                        {% else %}
                            {{ rand_name|random }}  
                        {% endif %}
                            {{ post.date_posted|date:"D, M d, Y" }} 
                    </p>
                    <p class="card-text">{{ post.content }}</p>
                </article>
            </div>
        </div>
    {% endfor %}
{% endblock content %}