mood/urls.py
from django.urls import path
from . import views
from .views import MoodCreateView, MoodListView, MoodDetailView, MoodUpdateView, MoodDeleteView

urlpatterns = [
    path('moods/', MoodListView.as_view(), name='mood-home'),
    path('moods/<int:pk>', MoodDetailView.as_view(), name='mood-detail'),  # pk primary key, int integer
    path('moods/<int:pk>/edit/', MoodUpdateView.as_view(), name='mood-edit'),
    path('moods/<int:pk>/delete/', MoodDeleteView.as_view(), name='mood-delete'),
    # path('moods/create', MoodCreateView.as_view(), name='mood-create'),
    path('moods/new/', views.mood_new, name='mood-new'),
    path('calendar/', views.display, name='mood-display'),
]

vibe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
    path('', include('mood.urls')),
    path('', include('customizer.urls')),
    path('', include('django.contrib.auth.urls'))

]

mood/models.py
from django.db import models
from django.utils import timezone
from django.utils.dateformat import format
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models import Q
from django.core.exceptions import ValidationError

# Create your models here.
class Mood(models.Model):
    # has own table in db
    MOODS = (
        (0, "Very Negative"),
        (1, "Negative"),
        (2, "Neutral"),
        (3, "Positive"),
        (4, "Very Positive"),
    )
    mood = models.PositiveSmallIntegerField(choices=MOODS)
    date_posted = models.DateField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(default="")

    class Meta:
        unique_together = [['date_posted', 'author']]

    def __str__(self):
        return str(self.mood)

    def to_list(self):
        return [int(format(self.date_posted, 'U')) * 1000, int(self.mood)]

    def get_absolute_url(self):
        return reverse('mood-detail', kwargs={'pk': self.pk})

    def display(self):
        return ["Very Negative", "Negative", "Neutral", "Positive", "Very Positive"][self.mood]

    def is_valid(self):
        query = "select id FROM mood_mood WHERE author_id = {0} AND date_posted = '{1}'".format(self.author_id, self.date_posted.strftime('%Y-%m-%d'))
        print("Query => ", query)
        results = Mood.objects.raw(query)
        return len(results) == 0

mood/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect
from django.utils.safestring import mark_safe

from .models import Mood
from customizer.models import Customizer
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView
from datetime import date
from datetime import datetime

# Create your views here.
class CustomLoginRequiredMixin(LoginRequiredMixin):
    """ The LoginRequiredMixin extended to add a relevant message to the
    messages framework by setting the ``permission_denied_message``
    attribute. """
    permission_denied_message = 'You have to be logged in to perform that action'
    user_permission_denied_message = 'You do not have permission to perform that action'
    user_permission_view_message = 'You do not have permission to perform that action'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.add_message(request, messages.WARNING,
                                 self.user_permission_view_message)
            return self.handle_no_permission()
        return super(CustomLoginRequiredMixin, self).dispatch(
            request, *args, **kwargs
        )

class CustomizerLoader():
    def get_context_data(self):
        context = dict()
        setting = Customizer.objects.filter(user=self.request.user)
        if setting:
            setting = setting[0]
            context.update({"nav_color": setting.theme_nav,
                            "bg_color": setting.theme_background,
                            "font_size": setting.font_size,
                            "font_style": setting.font_style})
        return context

# List of moods
class MoodListView(CustomLoginRequiredMixin, ListView, CustomizerLoader):
    model = Mood
    login_url = "login"
    context_object_name = 'moods'

    def get_context_data(self, **kwargs):
        context = ListView.get_context_data(self, **kwargs)
        context.update(CustomizerLoader.get_context_data(self))
        return context

    def get_queryset(self):
        return Mood.objects.filter(author=self.request.user).order_by('-date_posted')

# View a mood
class MoodDetailView(CustomLoginRequiredMixin, DetailView, CustomizerLoader):
    model = Mood
    login_url = "login"

    def get_context_data(self, **kwargs):
        context = DetailView.get_context_data(self, **kwargs)
        context.update(CustomizerLoader.get_context_data(self))
        return context

    def get_queryset(self):
        return get_mood_queryset(MoodDetailView, self, self.user_permission_denied_message)

# Create a mood
class MoodCreateView(CustomLoginRequiredMixin, CreateView, CustomizerLoader):
    # Redirect if not authenticated
    login_url = '/login/'

    model = Mood
    fields = ['mood', 'date_posted']
    success_url = "/moods"

    # The form has been already validated
    def form_valid(self, form):
        form.instance.author = self.request.user
        messages.add_message(self.request, messages.SUCCESS,
                             "Mood created successfully")
        result = super().form_valid(form)
        return result

    def get_context_data(self, **kwargs):
        context = CreateView.get_context_data(self, **kwargs)
        context.update(CustomizerLoader.get_context_data(self))
        return context

    def get_queryset(self):
        return get_mood_queryset(MoodUpdateView, self, self.user_permission_denied_message)

# Update a mood
class MoodUpdateView(CustomLoginRequiredMixin, UpdateView, CustomizerLoader):
    login_url = '/login/'

    model = Mood
    fields = ['mood', 'date_posted', 'content']
    success_url = "/moods"

    def form_valid(self, form):
        form.instance.author = self.request.user
        messages.add_message(self.request, messages.SUCCESS,
                                 "Mood was successfully updated.")
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = UpdateView.get_context_data(self, **kwargs)
        context.update(CustomizerLoader.get_context_data(self))
        return context

    def get_queryset(self):
        return get_mood_queryset(MoodUpdateView, self, self.user_permission_denied_message)

# Delete a mood
class MoodDeleteView(CustomLoginRequiredMixin, DeleteView, CustomizerLoader):
    login_url = '/login/'
    model = Mood
    success_url = "/moods"

    def get_context_data(self, **kwargs):
        context = DeleteView.get_context_data(self, **kwargs)
        context.update(CustomizerLoader.get_context_data(self))
        return context

    def get_queryset(self):
        return get_mood_queryset(MoodDeleteView, self, self.user_permission_denied_message)

    def delete(self, request, *args, **kwargs):
        messages.add_message(self.request, messages.SUCCESS,
                                 "Mood was successfully deleted.")
        return super(MoodDeleteView, self).delete(request, *args, **kwargs)

# Used to determine if the user has edit/delete permissions for the mood
def get_mood_queryset(MoodView, self, message):
    qs = super(MoodView, self).get_queryset()
    pk = self.kwargs.get('pk')
    if self.request.user.is_superuser:
        result = qs.filter(pk=pk)
    else:
        result = qs.filter(author_id=self.request.user.id).filter(pk=pk)
        if len(result.filter(pk=pk)) == 0: # Mood does not belong to user
            messages.add_message(self.request, messages.ERROR, message)
            raise PermissionDenied
    return result

@login_required
def display(request):

    the_moods = list(Mood.objects.filter(author=request.user).order_by('-date_posted'))
    values = [v.to_list() for v in the_moods]
    # unix time: date.replace(tzinfo=timezone.utc).timestamp()

    context = {
        'title': 'Display',
        'data': mark_safe(list(values)),  # works but only returns string value of mood
    }
    setting = Customizer.objects.filter(user=request.user)
    if setting:
        setting = setting[0]
        context.update({"nav_color": setting.theme_nav,
                        "bg_color": setting.theme_background,
                        "font_size": setting.font_size,
                        "font_style": setting.font_style})
    return render(request, 'charts/display.html', context)

# Form for creating a mood
def mood_new(request):
    if not request.user.is_authenticated:
        messages.add_message(request, messages.WARNING,
                             'You have to be logged in to perform that action')
        return redirect("/login")

    if request.method == 'POST':
        new_mood = Mood(request.POST)
        new_mood.mood = int(request.POST["mood"])
        new_mood.date_posted = datetime.fromisoformat(request.POST["date_posted"])
        new_mood.content = request.POST["content"]
        new_mood.author_id = request.user.id
        new_mood.id = None
        if new_mood.is_valid():
            new_mood.save()
            messages.add_message(request, messages.SUCCESS,
                                 "Mood was successfully created.")
            return redirect("/moods")
        else:
            messages.add_message(request, messages.WARNING,
                                 "Only one mood is allowed for one day.")
            context = dict()
            setting = Customizer.objects.filter(user=request.user)
            if setting:
                setting = setting[0]
                context.update({"nav_color": setting.theme_nav,
                                "bg_color": setting.theme_background,
                                "font_size": setting.font_size,
                                "font_style": setting.font_style})
            context.update({"object": new_mood})
            return render(request, 'mood/mood_form.html', context)

    else:
        new_mood = Mood()
        new_mood.date_posted = date.today()
        context = dict()
        setting = Customizer.objects.filter(user=request.user)
        if setting:
            setting = setting[0]
            context.update({"nav_color": setting.theme_nav,
                            "bg_color": setting.theme_background,
                            "font_size": setting.font_size,
                            "font_style": setting.font_style})
        context.update({"object": new_mood})
        return render(request, 'mood/mood_form.html', context)

mood/templates/mood/mood_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <div id="delete-mood" class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <h1>
                    <i class="fas fa-trash delete-warning"></i>
                    Delete Mood?
                </h1>
                <p>Mood entry on <b>{{ object.date_posted }}</b> will be removed.</p>
            </fieldset>
            <nav class="edit-actions">
                <button  id="confirm-ok-button" class="button btn delete-button" type="submit">Delete</button>
                <a class="button btn btn-light" href="/moods">Cancel</a>
            </nav>
        </form>
    </div>
{% endblock content %}

mood/templates/mood/mood_detail.html
{% extends "base.html" %}
{% block content %}
    <div>
        {# Display message if any exist (e.g. permission denied) #}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    </div>
    
    <div class="card bordered md:w-auto">
      <div class="card-body">
        <h1 class="card-title">{{ object.mood }}</h1>
        {# Django Date Documentation: https://docs.djangoproject.com/en/2.0/ref/templates/builtins/#date #}
        <h4 class="card-subtitle">By {{ object.author }} | {{ object.date_posted|date:"D, M d, Y" }} </h4>
        <p class="card-text">{{ object.content }}</p>
      </div>
    </div>
{% endblock content %}

mood/templates/mood/mood_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% block content %}

    <div id="mood-form" class="content-section">

        <!-- Display warning messages -->
        <div>
            {# Display message if any exist (e.g. permission denied) #}
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        </div>

        <!-- Title display for different modes -->
        {% if mood.id %}
            <legend>Editing Mood</legend>
        {% else %}
            <legend>Enter Today's Mood</legend>
        {% endif %}

        <!-- Form for posting or editing mood entry -->
        <form method="POST">
            {% csrf_token %}

            {# Date if editing only #}
                <fieldset class="form-group" {% if settings.DJANGO_ENV != "development" %}style="display:none;"{% endif %}>
                    <label class="">Date <span class="mandatory">*</span></label>
                    <input id="id_date" value="{{ object.date_posted  | date:'Y-m-d' }}" type="date"
                           name="date_posted" />
                </fieldset>
            {# Mood Selection #}
            <fieldset class="form-group">
                <label class="">Mood <span class="mandatory">*</span></label>
                <select id="id_mood" name="mood" class="select" required="">
                    <option value="">---</option>
                    <option {% if object.mood == 0 %} selected="" {% endif %} value="0">Very Negative</option>
                    <option {% if object.mood == 1 %} selected  {% endif %} value="1">Negative</option>
                    <option {% if object.mood == 2 %} selected  {% endif %} value="2">Neutral</option>
                    <option {% if object.mood == 3 %} selected  {% endif %} value="3">Positive</option>
                    <option {% if object.mood == 4 %} selected  {% endif %} value="4">Very Positive</option>
                </select>
            </fieldset>

            {# Daily Reflection #}
            <fieldset class="form-group">
                <label for="id_content" class="">Describe why you feel this way:</label>
                <textarea id="id_content" name="content">{{ object.content }}</textarea>
            </fieldset>

            <nav class="edit-actions">
                <button id="save-mood-btn" class="btn button confirm-button" type="submit">Save</button>
                <a href="/moods" id="cancel-btn" class="btn button btn-light">Cancel</a>
            </nav>
        </form>
    </div>
{% endblock content %}

mood/templates/mood/mood_list.html
{% extends "base.html" %}
{% block content %}

    <div>
        <h1>My Moods</h1>
    </div>

    <div>
        <a class="btn btn-info mood-link" href="/calendar">
            <i class="fa fa-chart-line"></i>
            Go to Graph View
        </a>
    </div>

    <div>
        {# Display message if any exist (e.g. permission denied) #}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    </div>

    <section class="mood-list">
        <!-- Link to create new mood entry -->
        <a href="/moods/new" id="new-mood-link" class="button">
            <i class="fa fa-plus"></i> 
            <p>Create New Mood Entry</p>
        </a>
        
        <!-- Mood Entries -->
        {% for mood in moods %}
        <div class="card mood-entry">
            <h2>{{  mood.display }}</h2>

            {# Django Date Documentation: https://docs.djangoproject.com/en/2.0/ref/templates/builtins/#date #}
            <p>{{ mood.date_posted|date:"D, M d, Y" }}</p>
            <p class="mood-content">{{ mood.content }}</p>
            <nav class="mood-actions">
                <!-- Edit button -->
                <a href="{% url 'mood-edit' mood.id %}" class="btn btn-light mood-edit"><i class="fa fa-edit"></i>Edit</a>
                <!-- Delete button -->
                <a data-confirm="Are you sure?" class="btn mood-delete" rel="nofollow" data-method="delete"
                href="{% url 'mood-delete' mood.id %}"><i class="fa fa-trash"></i>Delete</a>
            </nav>
        </div>
        {% endfor %}
    </section>

{% endblock content %}